[package]
name = "popup_dictionary"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
curl = "0.4.47"
serde_json = "1.0.140"
serde = "1.0.219"
vibrato = "0.5.2"
sled = "0.34.7"
bincode = "2.0.1"
